files: 
  - 
    destination: /home/incites/ftp/files/testRepository
    source: /
hooks: 
  AfterInstall: 
    - 
      location: scripts/install.sh
      runas: root
      timeout: 300
  ApplicationStart: 
    - 
      location: scripts/start.sh
      runas: root
      timeout: 60
os: linux